name: postgres-service

on: [push]

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for PostgreSQL service
        run: |
          echo "⏳ Waiting for PostgreSQL to start..."
          until nc -z localhost 5432; do
            echo "Waiting..."
            sleep 1
          done
          echo "✅ PostgreSQL is ready!"

